### ISSUE TITLE
[ERROR] Hydration error on refreshing the page

### ISSUE THREAD

**Issue by piotrostr** [asoltd/guilds#71]
* Reproduce:

`bun next dev` and refresh the page twice

* Error

<img width="869" alt="image" src="https://user-images.githubusercontent.com/63755291/198833401-bf94e69a-5dd5-4072-9dab-30343f2c0be4.png">

https://nextjs.org/docs/messages/react-hydration-error

**Comment by OliwierOST** [comment]
Resolved in #72

**Comment by piotrostr** [comment]
This was not fixed in #72, only refactored there

**Comment by piotrostr** [comment]
fixed in #75
